### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SuperAdam47** [thebigsmileXD/ItemFrameCommands#3]
[Server thread/CRITICAL]: Error: "Class 'xenialdan\customui\windows\CustomForm' not found" (EXCEPTION) in "plugins/ItemFrameCommands-master/src/xenialdan/ItemFrameCommands/subcommand/AddSubCommand" at line 24

**Comment by inxomnyaa** [comment]
Do not run it from source if you do not know how to use/load required virions

**Comment by SuperAdam47** [comment]
phar not found

**Comment by inxomnyaa** [comment]
I removed forms since they are not needed anymore- re-fixed lol
