### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuperAdam47** [thebigsmileXD/ItemFrameCommands#4]
[09:53:13] [Server thread/CRITICAL]: Error: "Call to a member function getAllValues() on null" (EXCEPTION) in "plugins/ItemFrameCommands_dev-3.phar/src/xenialdan/ItemFrameCommands/EventListener" at line 97

lastest ItemFrameCommands version PMMP API 3.6.1

**Comment by SuperAdam47** [comment]
@thebigsmileXD

**Comment by inxomnyaa** [comment]
Fixed

**Comment by SuperAdam47** [comment]
Thanks

**Comment by inxomnyaa** [comment]
Welcome :) do you have time to check if everything is working? Need some testers

**Comment by SuperAdam47** [comment]
I try to test it tomorrow. :)

**Comment by SuperAdam47** [comment]
![image](https://user-images.githubusercontent.com/16169771/66378952-35126700-e9bd-11e9-8965-760247401d76.png)
How to setup i dont understood

**Comment by SuperAdam47** [comment]
[Server thread/CRITICAL]: ErrorException: "Undefined index: as:player" (EXCEPTION) in "C:/Users/EMREY/Desktop/Test-Sunucu/virions/Commando_dev-25.phar/src/CortexPE/Commando/args/StringEnumArgument" at line 66


[Server thread/CRITICAL]: ErrorException: "Undefined index: as:console" (EXCEPTION) in "C:/Users/EMREY/Desktop/Test-Sunucu/virions/Commando_dev-25.phar/src/CortexPE/Commando/args/StringEnumArgument" at line 66

**Comment by inxomnyaa** [comment]
Huh? Weird.

Can you try running a precompiled phar instead?

**Comment by inxomnyaa** [comment]
Huh? Weird.

Can you try running a precompiled phar instead?

**Comment by SuperAdam47** [comment]
I learned.
worked plugin tested commands:

/frame addcmd player gamemode 1
/frame setitem
/frame setname yeah
/frame list
/frame delcmd

**Comment by inxomnyaa** [comment]
Ah. Also wrong command usage
/help frame addcmd
;)

/frame addcmd player|console say hi {player}

**Comment by SuperAdam47** [comment]
yes .d
installation can be difficult for some.
UI support would be good

**Comment by inxomnyaa** [comment]
I removed ui support since it was just unnecessary and the command field was tiny in comparison to the chat/command window

I will think about a way to simplify the setup and add some explainations to the readme - Thank you for your testing and feedback!
